# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_cni
- name: istio_cni_postsubmit
- name: istio_cri
- name: istio_cri_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_envoy
- name: istio_gogo-genproto
- name: istio_gogo-genproto_postsubmit
- name: istio_infrastructure
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio.io_periodic
- name: istio_istio_postsubmit
- name: istio_pkg
- name: istio_pkg_postsubmit
- name: istio_proxy
- name: istio_proxy_postsubmit

- name: istio_release-1.4_istio_postsubmit
- name: istio_release-1.4_client-go_postsubmit
- name: istio_release-1.4_cni_postsubmit
- name: istio_release-1.4_common-files_postsubmit
- name: istio_release-1.4_gogo-genproto_postsubmit
- name: istio_release-1.4_istio.io_postsubmit
- name: istio_release-1.4_operator_postsubmit
- name: istio_release-1.4_pkg_postsubmit
- name: istio_release-1.4_proxy_postsubmit
- name: istio_release-1.4_api_postsubmit
- name: istio_release-1.4_installer_postsubmit
- name: istio_release-1.4_tools_postsubmit
- name: istio_release-1.4_release-builder_postsubmit

- name: istio_release-1.5_istio
- name: istio_release-1.5_api
- name: istio_release-1.5_client-go
- name: istio_release-1.5_cni
- name: istio_release-1.5_common-files
- name: istio_release-1.5_envoy
- name: istio_release-1.5_gogo-genproto
- name: istio_release-1.5_istio.io
- name: istio_release-1.5_pkg
- name: istio_release-1.5_proxy
- name: istio_release-1.5_tools
- name: istio_release-1.5_release-builder

- name: istio_release-1.5_istio_postsubmit
- name: istio_release-1.5_client-go_postsubmit
- name: istio_release-1.5_cni_postsubmit
- name: istio_release-1.5_common-files_postsubmit
- name: istio_release-1.5_gogo-genproto_postsubmit
- name: istio_release-1.5_istio.io_postsubmit
- name: istio_release-1.5_pkg_postsubmit
- name: istio_release-1.5_proxy_postsubmit
- name: istio_release-1.5_api_postsubmit
- name: istio_release-1.5_tools_postsubmit
- name: istio_release-1.5_release-builder_postsubmit

- name: istio_release-1.4_istio
- name: istio_release-1.4_api
- name: istio_release-1.4_client-go
- name: istio_release-1.4_cni
- name: istio_release-1.4_common-files
- name: istio_release-1.4_envoy
- name: istio_release-1.4_gogo-genproto
- name: istio_release-1.4_istio.io
- name: istio_release-1.4_operator
- name: istio_release-1.4_pkg
- name: istio_release-1.4_proxy
- name: istio_release-1.4_installer
- name: istio_release-1.4_tools
- name: istio_release-1.4_release-builder

- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_release-pipeline
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_test-infra_periodic
- name: istio_tools
- name: istio_tools_postsubmit

# Group all dashboards
dashboard_groups:
- name: istio_release-1.5
  dashboard_names:
  - istio_release-1.5_istio_postsubmit
  - istio_release-1.5_client-go_postsubmit
  - istio_release-1.5_cni_postsubmit
  - istio_release-1.5_common-files_postsubmit
  - istio_release-1.5_gogo-genproto_postsubmit
  - istio_release-1.5_istio.io_postsubmit
  - istio_release-1.5_pkg_postsubmit
  - istio_release-1.5_proxy_postsubmit
  - istio_release-1.5_api_postsubmit
  - istio_release-1.5_tools_postsubmit
  - istio_release-1.5_release-builder_postsubmit

  - istio_release-1.5_istio
  - istio_release-1.5_api
  - istio_release-1.5_client-go
  - istio_release-1.5_cni
  - istio_release-1.5_common-files
  - istio_release-1.5_envoy
  - istio_release-1.5_gogo-genproto
  - istio_release-1.5_istio.io
  - istio_release-1.5_pkg
  - istio_release-1.5_proxy
  - istio_release-1.5_tools
  - istio_release-1.5_release-builder

- name: istio_release-1.4
  dashboard_names:
  - istio_release-1.4_istio_postsubmit
  - istio_release-1.4_client-go_postsubmit
  - istio_release-1.4_cni_postsubmit
  - istio_release-1.4_common-files_postsubmit
  - istio_release-1.4_gogo-genproto_postsubmit
  - istio_release-1.4_istio.io_postsubmit
  - istio_release-1.4_operator_postsubmit
  - istio_release-1.4_pkg_postsubmit
  - istio_release-1.4_proxy_postsubmit
  - istio_release-1.4_api_postsubmit
  - istio_release-1.4_installer_postsubmit
  - istio_release-1.4_tools_postsubmit
  - istio_release-1.4_release-builder_postsubmit

  - istio_release-1.4_istio
  - istio_release-1.4_api
  - istio_release-1.4_client-go
  - istio_release-1.4_cni
  - istio_release-1.4_common-files
  - istio_release-1.4_envoy
  - istio_release-1.4_gogo-genproto
  - istio_release-1.4_istio.io
  - istio_release-1.4_operator
  - istio_release-1.4_pkg
  - istio_release-1.4_proxy
  - istio_release-1.4_installer
  - istio_release-1.4_tools
  - istio_release-1.4_release-builder

- name: istio
  dashboard_names:
  - istio_istio.io_periodic
  - istio_test-infra_periodic

  - istio_istio_postsubmit
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_cni_postsubmit
  - istio_cri_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_gogo-genproto_postsubmit
  - istio_istio.io_postsubmit
  - istio_pkg_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tools_postsubmit

  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_cni
  - istio_cri
  - istio_common-files
  - istio_community
  - istio_envoy
  - istio_gogo-genproto
  - istio_infrastructure
  - istio_istio.io
  - istio_pkg
  - istio_proxy
  - istio_test-infra
  - istio_tools
