# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_cri
- name: istio_cri_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_envoy
- name: istio_envoy_periodic
- name: istio_gogo-genproto
- name: istio_gogo-genproto_postsubmit
- name: istio_infrastructure
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio.io_periodic
- name: istio_istio_postsubmit
- name: istio_pkg
- name: istio_pkg_postsubmit
- name: istio_proxy
- name: istio_proxy_postsubmit

- name: istio_release-1.8_istio
- name: istio_release-1.8_api
- name: istio_release-1.8_client-go
- name: istio_release-1.8_common-files
- name: istio_release-1.8_envoy
- name: istio_release-1.8_gogo-genproto
- name: istio_release-1.8_istio.io
- name: istio_release-1.8_pkg
- name: istio_release-1.8_proxy
- name: istio_release-1.8_tools
- name: istio_release-1.8_release-builder

- name: istio_release-1.8_istio_postsubmit
- name: istio_release-1.8_client-go_postsubmit
- name: istio_release-1.8_common-files_postsubmit
- name: istio_release-1.8_gogo-genproto_postsubmit
- name: istio_release-1.8_istio.io_postsubmit
- name: istio_release-1.8_pkg_postsubmit
- name: istio_release-1.8_proxy_postsubmit
- name: istio_release-1.8_api_postsubmit
- name: istio_release-1.8_tools_postsubmit
- name: istio_release-1.8_release-builder_postsubmit

- name: istio_release-1.7_istio
- name: istio_release-1.7_api
- name: istio_release-1.7_client-go
- name: istio_release-1.7_common-files
- name: istio_release-1.7_envoy
- name: istio_release-1.7_gogo-genproto
- name: istio_release-1.7_istio.io
- name: istio_release-1.7_pkg
- name: istio_release-1.7_proxy
- name: istio_release-1.7_tools
- name: istio_release-1.7_release-builder

- name: istio_release-1.7_istio_postsubmit
- name: istio_release-1.7_client-go_postsubmit
- name: istio_release-1.7_common-files_postsubmit
- name: istio_release-1.7_gogo-genproto_postsubmit
- name: istio_release-1.7_istio.io_postsubmit
- name: istio_release-1.7_pkg_postsubmit
- name: istio_release-1.7_proxy_postsubmit
- name: istio_release-1.7_api_postsubmit
- name: istio_release-1.7_tools_postsubmit
- name: istio_release-1.7_release-builder_postsubmit

- name: istio_release-1.6_istio
- name: istio_release-1.6_api
- name: istio_release-1.6_client-go
- name: istio_release-1.6_cni
- name: istio_release-1.6_common-files
- name: istio_release-1.6_envoy
- name: istio_release-1.6_gogo-genproto
- name: istio_release-1.6_istio.io
- name: istio_release-1.6_pkg
- name: istio_release-1.6_proxy
- name: istio_release-1.6_tools
- name: istio_release-1.6_release-builder

- name: istio_release-1.6_istio_postsubmit
- name: istio_release-1.6_client-go_postsubmit
- name: istio_release-1.6_cni_postsubmit
- name: istio_release-1.6_common-files_postsubmit
- name: istio_release-1.6_gogo-genproto_postsubmit
- name: istio_release-1.6_istio.io_postsubmit
- name: istio_release-1.6_pkg_postsubmit
- name: istio_release-1.6_proxy_postsubmit
- name: istio_release-1.6_api_postsubmit
- name: istio_release-1.6_tools_postsubmit
- name: istio_release-1.6_release-builder_postsubmit

- name: istio_release-1.5_istio
- name: istio_release-1.5_api
- name: istio_release-1.5_client-go
- name: istio_release-1.5_cni
- name: istio_release-1.5_common-files
- name: istio_release-1.5_envoy
- name: istio_release-1.5_gogo-genproto
- name: istio_release-1.5_istio.io
- name: istio_release-1.5_pkg
- name: istio_release-1.5_proxy
- name: istio_release-1.5_tools
- name: istio_release-1.5_release-builder

- name: istio_release-1.5_istio_postsubmit
- name: istio_release-1.5_client-go_postsubmit
- name: istio_release-1.5_cni_postsubmit
- name: istio_release-1.5_common-files_postsubmit
- name: istio_release-1.5_gogo-genproto_postsubmit
- name: istio_release-1.5_istio.io_postsubmit
- name: istio_release-1.5_pkg_postsubmit
- name: istio_release-1.5_proxy_postsubmit
- name: istio_release-1.5_api_postsubmit
- name: istio_release-1.5_tools_postsubmit
- name: istio_release-1.5_release-builder_postsubmit


- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_release-pipeline
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_test-infra_periodic
- name: istio_tools
- name: istio_tools_postsubmit

# Group all dashboards
dashboard_groups:
- name: istio_release-1.8
  dashboard_names:
  - istio_release-1.8_istio_postsubmit
  - istio_release-1.8_client-go_postsubmit
  - istio_release-1.8_common-files_postsubmit
  - istio_release-1.8_gogo-genproto_postsubmit
  - istio_release-1.8_istio.io_postsubmit
  - istio_release-1.8_pkg_postsubmit
  - istio_release-1.8_proxy_postsubmit
  - istio_release-1.8_api_postsubmit
  - istio_release-1.8_tools_postsubmit
  - istio_release-1.8_release-builder_postsubmit

  - istio_release-1.8_istio
  - istio_release-1.8_api
  - istio_release-1.8_client-go
  - istio_release-1.8_common-files
  - istio_release-1.8_envoy
  - istio_release-1.8_gogo-genproto
  - istio_release-1.8_istio.io
  - istio_release-1.8_pkg
  - istio_release-1.8_proxy
  - istio_release-1.8_tools
  - istio_release-1.8_release-builder

- name: istio_release-1.7
  dashboard_names:
  - istio_release-1.7_istio_postsubmit
  - istio_release-1.7_client-go_postsubmit
  - istio_release-1.7_common-files_postsubmit
  - istio_release-1.7_gogo-genproto_postsubmit
  - istio_release-1.7_istio.io_postsubmit
  - istio_release-1.7_pkg_postsubmit
  - istio_release-1.7_proxy_postsubmit
  - istio_release-1.7_api_postsubmit
  - istio_release-1.7_tools_postsubmit
  - istio_release-1.7_release-builder_postsubmit

  - istio_release-1.7_istio
  - istio_release-1.7_api
  - istio_release-1.7_client-go
  - istio_release-1.7_common-files
  - istio_release-1.7_envoy
  - istio_release-1.7_gogo-genproto
  - istio_release-1.7_istio.io
  - istio_release-1.7_pkg
  - istio_release-1.7_proxy
  - istio_release-1.7_tools
  - istio_release-1.7_release-builder

- name: istio_release-1.6
  dashboard_names:
  - istio_release-1.6_istio_postsubmit
  - istio_release-1.6_client-go_postsubmit
  - istio_release-1.6_cni_postsubmit
  - istio_release-1.6_common-files_postsubmit
  - istio_release-1.6_gogo-genproto_postsubmit
  - istio_release-1.6_istio.io_postsubmit
  - istio_release-1.6_pkg_postsubmit
  - istio_release-1.6_proxy_postsubmit
  - istio_release-1.6_api_postsubmit
  - istio_release-1.6_tools_postsubmit
  - istio_release-1.6_release-builder_postsubmit

  - istio_release-1.6_istio
  - istio_release-1.6_api
  - istio_release-1.6_client-go
  - istio_release-1.6_cni
  - istio_release-1.6_common-files
  - istio_release-1.6_envoy
  - istio_release-1.6_gogo-genproto
  - istio_release-1.6_istio.io
  - istio_release-1.6_pkg
  - istio_release-1.6_proxy
  - istio_release-1.6_tools
  - istio_release-1.6_release-builder

- name: istio_release-1.5
  dashboard_names:
  - istio_release-1.5_istio_postsubmit
  - istio_release-1.5_client-go_postsubmit
  - istio_release-1.5_cni_postsubmit
  - istio_release-1.5_common-files_postsubmit
  - istio_release-1.5_gogo-genproto_postsubmit
  - istio_release-1.5_istio.io_postsubmit
  - istio_release-1.5_pkg_postsubmit
  - istio_release-1.5_proxy_postsubmit
  - istio_release-1.5_api_postsubmit
  - istio_release-1.5_tools_postsubmit
  - istio_release-1.5_release-builder_postsubmit

  - istio_release-1.5_istio
  - istio_release-1.5_api
  - istio_release-1.5_client-go
  - istio_release-1.5_cni
  - istio_release-1.5_common-files
  - istio_release-1.5_envoy
  - istio_release-1.5_gogo-genproto
  - istio_release-1.5_istio.io
  - istio_release-1.5_pkg
  - istio_release-1.5_proxy
  - istio_release-1.5_tools
  - istio_release-1.5_release-builder

- name: istio
  dashboard_names:
  - istio_istio.io_periodic
  - istio_test-infra_periodic

  - istio_istio_postsubmit
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_cri_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_gogo-genproto_postsubmit
  - istio_istio.io_postsubmit
  - istio_pkg_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tools_postsubmit

  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_cri
  - istio_common-files
  - istio_community
  - istio_envoy
  - istio_envoy_periodic
  - istio_gogo-genproto
  - istio_infrastructure
  - istio_istio.io
  - istio_pkg
  - istio_proxy
  - istio_test-infra
  - istio_tools
