apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prow-monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          # ATTENTION: Keep this in sync with the list in mixins/prometheus/lib/config.libsonnet
          - https://prow.istio.io
          - https://monitoring.prow.istio.io
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-prober
type: Opaque
