apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  labels:
    app.kubernetes.io/part-of: prow
  name: monitoring-prow-istio-io
  namespace: prow-monitoring
spec:
  domains:
  - monitoring.prow.istio.io