### Please modify PASSWORD before
### kubectl apply -f grafana_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: prow-monitoring
  name: prow-grafana
type: Opaque
stringData:
  password: PASSWORD
