defaults:
  mapping:
    istio: istio-private
  input: ./prow/cluster/jobs/
  output: ./prow/cluster/jobs/
  ssh-clone: true
  refs: true
  cluster: private
  modifier: priv
  annotations:
    testgrid-create-test-group: "false"
  volume-denylist: [build-cache-pvc]