defaults:
  branches: [release-1.7]
  repo-allowlist: [api]


transforms:

# istio/api build job(s) - presubmit(s)
- env:
    GCS_BUCKET: istio-private-build/dev
  labels:
    preset-enable-ssh: "true"
    preset-override-deps: release-1.7-istio
  job-type: [presubmit]
  job-allowlist: [build, gencheck]
  job-denylist: [release-notes]

# istio/api test jobs(s) - postsubmit(s)
- labels:
    preset-enable-ssh: "true"
  job-type: [postsubmit]
  job-denylist: [update_api_dep]
