defaults:
  branches:
  - release-1.17
  repo-allowlist:
  - api
org: istio
repo: api
transforms:
- env:
    GCS_BUCKET: istio-build-private/dev
  job-allowlist:
  - build_release-1.17
  - gencheck_release-1.17
  job-type:
  - presubmit
- job-allowlist:
  - build
  - gencheck
  job-type:
  - postsubmit
