defaults:
  branches:
  - release-1.17
  repo-allowlist:
  - api
org: istio
repo: api
transforms:
- env:
    GCS_BUCKET: istio-private-build/dev
  job-allowlist:
  - build_release-1.17
  - gencheck_release-1.17
  job-denylist:
  - release-notes_release-1.17
  job-type:
  - presubmit
  labels:
    preset-enable-ssh: "true"
- job-allowlist:
  - build
  - gencheck
  job-type:
  - postsubmit
  labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
