org: istio
repo: api
support_release_branching: true

defaults:
  branches: [master]
  repo-allowlist: [api]


transforms:

# istio/api master build job(s) - presubmit(s)
- env:
    GCS_BUCKET: istio-build-private/dev
  labels:
    preset-enable-ssh: "true"
  job-type: [presubmit]
  job-allowlist: [build, gencheck]

# istio/api master test jobs(s) - postsubmit(s)
- labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
  job-type: [postsubmit]
  job-allowlist: [build, gencheck]
