org: istio
repo: istio
support_release_branching: true

defaults:
  branches: [master]
  repo-allowlist: [istio]

transforms:

# istio/istio master build job(s) - postsubmit(s)
- env:
    DOCKER_HUB: us-docker.pkg.dev/istio-prow-private/istio-prow-private
    GCS_BUCKET: istio-build-private/dev
  labels:
    preset-enable-netrc: "true"
    preset-override-envoy: "true"
    preset-override-deps: master-istio
  job-type: [postsubmit]
  job-allowlist: [release_istio_postsubmit]

# istio/istio master test jobs(s) - presubmit(s) and postsubmit(s)
- labels:
    preset-enable-netrc: "true"
    preset-override-envoy: "true"
    preset-override-deps: master-istio
  job-type: [presubmit, postsubmit]
  job-denylist: [benchmark-report_istio_postsubmit, release_istio_postsubmit, release-notes_istio, build-base-images_istio]

