defaults:
  branches: [release-1.4]
  repo-allowlist: [istio]


transforms:

# istio/istio master build job(s) - postsubmit(s)
- env:
    DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-build/dev
  labels:
    preset-enable-ssh: "true"
    preset-enable-gomod-netrc: "true"
    preset-override-deps: release-1.4-istio
  job-type: [postsubmit]
  job-allowlist: [release_istio_release-1.4_postsubmit]

# istio/istio master test jobs(s) - presubmit(s) and postsubmit(s)
- labels:
    preset-enable-ssh: "true"
    preset-enable-gomod-netrc: "true"
    preset-override-envoy: "true"
    preset-override-deps: release-1.4-istio
  job-type: [presubmit, postsubmit]
  job-denylist: [release_istio_release-1.4_postsubmit]
