org: istio
repo: istio.io
support_release_branching: true

defaults:
  branches: [master]
  repo-allowlist: [istio.io]


transforms:
- job-type: [presubmit, postsubmit]
  job-denylist: [update-ref-docs-dry-run_istio.io]
