defaults:
  branches:
  - release-1.17
  repo-allowlist:
  - istio
org: istio
repo: istio
transforms:
- env:
    DOCKER_HUB: us-docker.pkg.dev/istio-prow-private/istio-prow-private
    GCS_BUCKET: istio-build-private/dev
  job-allowlist:
  - release_istio_release-1.17_postsubmit
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.17-istio
- job-denylist:
  - benchmark-report_istio_release-1.17_postsubmit
  - release_istio_release-1.17_postsubmit
  - release-notes_istio_release-1.17
  - build-base-images_istio_release-1.17
  job-type:
  - presubmit
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.17-istio
    preset-override-envoy: "true"