defaults:
  branches: [master, release-1.4, release-1.5, release-1.6]
  repo-whitelist: [istio.io]


transforms:
- job-type: [presubmit, postsubmit]
  job-blacklist: [update-ref-docs-dry-run_istio.io]