defaults:
  branches:
  - release-1.18
  modifier: release-1.18_priv
  repo-allowlist:
  - proxy
org: istio
repo: proxy
transforms:
- env:
    BAZEL_BUILD_RBE_INSTANCE: ""
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
  job-type:
  - presubmit
  labels:
    preset-enable-netrc: "true"
- env:
    BAZEL_BUILD_RBE_INSTANCE: ""
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    GCS_BUILD_BUCKET: istio-build-private
  job-denylist:
  - update-istio_proxy_release-1.18
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"