defaults:
  branches: [release-1.5]
  repo-allowlist: [proxy]
  modifier: release-1.5_priv


transforms:

# istio/proxy release-1.5 test jobs(s) - presubmit(s)
- env:
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]


# istio/proxy release-1.5 build jobs(s) - postsubmit(s)
- env:
    GCS_BUILD_BUCKET: istio-private-build
    GCS_ARTIFACTS_BUCKET: istio-private-artifacts
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
