defaults:
  branches: [master]
  repo-allowlist: [proxy]
  modifier: master_priv


transforms:

# istio/proxy master test jobs(s) - presubmit(s)
- env:
    ENVOY_REPOSITORY: https://github.com/envoyproxy/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]

# istio/proxy master build jobs(s) - postsubmit(s)
- env:
    GCS_BUILD_BUCKET: istio-private-build
    GCS_ARTIFACTS_BUCKET: istio-private-artifacts
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_REPOSITORY: https://github.com/envoyproxy/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
