defaults:
  branches: [release-1.6]
  repo-whitelist: [release-builder]


transforms:

# istio/release-builder release-1.6 test jobs(s) - pre/postsubmit(s)
- job-type: [presubmit, postsubmit]
  repo-whitelist: [release-builder]
  job-whitelist: [lint_release-builder_release-1.6,lint_release-builder_release-1.6_postsubmit,test_release-builder_release-1.6,test_release-builder_release-1.6_postsubmit,gencheck_release-builder_release-1.6,gencheck_release-builder_release-1.6_postsubmit]

# istio/release-builder release-1.6 build warning jobs(s) - presubmit(s)
- env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  job-type: [presubmit]
  repo-whitelist: [release-builder]
  job-whitelist: [build-warning_release-builder_release-1.6]

  # istio/release-builder release-1.6 build jobs(s) - postsubmit(s)
- env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
    preset-override-deps: release-1.6-release
  job-type: [postsubmit]
  repo-whitelist: [release-builder]
  job-whitelist: [build-release_release-builder_release-1.6_postsubmit]
