defaults:
  branches:
  - release-1.17
  repo-allowlist:
  - release-builder
org: istio
repo: release-builder
transforms:
- job-allowlist:
  - lint_release-builder_release-1.17
  - lint_release-builder_release-1.17_postsubmit
  - test_release-builder_release-1.17
  - test_release-builder_release-1.17_postsubmit
  - gencheck_release-builder_release-1.17
  - gencheck_release-builder_release-1.17_postsubmit
  job-type:
  - presubmit
  - postsubmit
  labels:
    preset-enable-netrc: "true"
  repo-allowlist:
  - release-builder
- env:
    GCS_BUCKET: istio-prerelease-private/prerelease
    HELM_BUCKET: istio-prerelease-private/charts
    PRERELEASE_DOCKER_HUB: us-docker.pkg.dev/istio-prow-private/istio-prow-private
  job-allowlist:
  - build-warning_release-builder_release-1.17
  job-type:
  - presubmit
  repo-allowlist:
  - release-builder
- env:
    GCS_BUCKET: istio-prerelease-private/prerelease
    HELM_BUCKET: istio-prerelease-private/charts
    PRERELEASE_DOCKER_HUB: us-docker.pkg.dev/istio-prow-private/istio-prow-private
    GCP_SECRETS: null # Don't use their secrets. We only need to push to GCS and GCR which do not need secrets
  job-allowlist:
  - build-release_release-builder_release-1.17_postsubmit
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.17-release
    preset-override-envoy: "true"
  repo-allowlist:
  - release-builder
