---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: istio-prow-test-job-default@istio-testing.iam.gserviceaccount.com
  namespace: test-pods
  # Default service account that only has permissions to access the GCS bucket for logging.
  name: prowjob-default-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prowjob-release@istio-prow-build.iam.gserviceaccount.com
  namespace: test-pods
  # Service account that has permissions for release jobs.
  # This should ONLY be used for release jobs.
  name: prowjob-release
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prowjob-rbe@istio-prow-build.iam.gserviceaccount.com
  namespace: test-pods
  # Service account that has permissions for RBE access. For use by istio/proxy
  name: prowjob-rbe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prowjob-build-tools@istio-prow-build.iam.gserviceaccount.com
  namespace: test-pods
  # Service account that has permissions to push to gcr.io/istio-testing and to push PRs as istio-testing account.
  name: prowjob-build-tools
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prowjob-testing-write@istio-prow-build.iam.gserviceaccount.com
  namespace: test-pods
  # Service account that has permissions to push to gcr.io/istio-testing and gs://istio-build.
  name: prowjob-testing-write
