apiVersion: v1
kind: Service
metadata:
  labels:
    app: crier
    app.kubernetes.io/part-of: prow
  namespace: default
  name: crier
spec:
  ports:
  - name: metrics
    port: 9090
  selector:
    app: crier
