apiVersion: apps/v1
kind: Deployment
metadata:
  name: crier
  labels:
    app.kubernetes.io/part-of: prow
    app: crier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crier
  template:
    metadata:
      labels:
        app: crier
    spec:
      # serviceAccountName: crier
      terminationGracePeriodSeconds: 30
      containers:
      - name: crier
        image: gcr.io/k8s-prow/crier:v20200507-36c6a27f0
        args:
        - --github-workers=5
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        - --slack-workers=1
        - --slack-token-file=/etc/slack/token
        - --gcs-workers=1
        - --kubernetes-gcs-workers=1
        - --gcs-credentials-file=/etc/service-account/service-account.json
        - --kubeconfig=/etc/kubeconfig/istio-config
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: slack
          mountPath: /etc/slack
          readOnly: true
        - name: service-account
          mountPath: /etc/service-account
          readOnly: true
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: slack
        secret:
          secretName: slack-token
      - name: service-account
        secret:
          secretName: prow-service-account
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
