apiVersion: v1
kind: Service
metadata:
  labels:
    app: horologium
    app.kubernetes.io/part-of: prow
  namespace: default
  name: horologium
spec:
  ports:
    - name: metrics
      port: 9090
  selector:
    app: horologium
