---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: prow-grafana
  namespace: prow-monitoring
  labels:
    app.kubernetes.io/part-of: prow
spec:
  backendType: gcpSecretsManager
  projectId: istio-testing
  data:
  - key: istio-prow__prow-monitoring__grafana
    name: password
    version: latest
