apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plank
  labels:
    app.kubernetes.io/part-of: prow
    app: plank
spec:
  replicas: 1 # Do not scale up
  template:
    metadata:
      labels:
        app: plank
    spec:
      containers:
      - name: plank
        image: gcr.io/k8s-prow/plank:v20200526-c96f7e37b
        args:
        - --config-path=/etc/config/config.yaml
        - --dry-run=false
        - --job-config-path=/etc/job-config
        - --tot-url=http://tot
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --kubeconfig=/etc/kubeconfig/istio-config
        - --skip-report=true
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
