apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-mason
  labels:
    app.kubernetes.io/part-of: boskos
    app: boskos-mason
  namespace: boskos
spec:
  selector:
    matchLabels:
      app: boskos-mason
  replicas: 5
  template:
    metadata:
      labels:
        app: boskos-mason
    spec:
      serviceAccountName: boskos-admin
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-mason
        image: gcr.io/istio-testing/mason:v20200311-1.5.0-40-gfc8ffb89
        args:
        - --service-account=/etc/service-account/service-account.json
        - --cleaner-count=25
        - --namespace=boskos
        volumeMounts:
        - mountPath: /etc/service-account
          name: service-account
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: boskos-service-account
      tolerations:
      - key: dedicated
        operator: Equal
        value: boskos
        effect: NoSchedule
      nodeSelector:
        prod: boskos
