branches:
- release-1.5
image: gcr.io/istio-testing/build-tools:release-1.5-2020-05-11T22-26-45
jobs:
- command:
  - make
  - presubmit
  name: build
- command:
  - make
  - gen-check
  name: gencheck
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=client-go
  - '--title=Automator: update istio/api@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge
  - --modifier=client-go_update_api
  - --token-path=/etc/github-token/oauth
  - --cmd=go get istio.io/api@$AUTOMATOR_SHA && go mod tidy && make clean gen
  name: gen_client-go
  repos:
  - istio/test-infra@master
  requirements:
  - github
  type: postsubmit
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio
  - '--title=Automator: update istio/api@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge
  - --modifier=istio_update_api
  - --token-path=/etc/github-token/oauth
  - --cmd=go get istio.io/api@$AUTOMATOR_SHA && go mod tidy && make clean gen
  name: gen_istio
  repos:
  - istio/test-infra@master
  requirements:
  - github
  type: postsubmit
org: istio
repo: api
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
