org: istio
repo: api
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2021-01-29T01-18-46

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]

  - name: update_api_dep
    types: [postsubmit]
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio,client-go
    - "--title=Automator: update istio/api@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --labels=auto-merge,release-notes-none
    - --modifier=update_api_dep
    - --token-path=/etc/github-token/oauth
    - --cmd=go get istio.io/api@$AUTOMATOR_SHA && go mod tidy && make clean gen
    requirements: [github]
    repos: [istio/test-infra@master]

  - name: release-notes
    types: [presubmit]
    modifiers: [optional]
    command:
      - ../test-infra/tools/check_release_notes.sh
      - --token-path=/etc/github-token/oauth
    requirements: [github]
    repos: [istio/test-infra@master,istio/tools@master]
