org: istio
repo: api
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-08-12T13-43-22

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]

  - name: update_api_dep
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio,client-go
    - "--title=Automator: update istio/api@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --labels=auto-merge,release-notes-none
    - --modifier=update_api_dep
    - --token-path=/etc/github-token/oauth
    - --cmd=go get istio.io/api@$AUTOMATOR_SHA && go mod tidy && make clean gen
    requirements: [github]
    repos: [istio/test-infra@master]
