branches:
- release-1.7
image: gcr.io/istio-testing/build-tools:release-1.7-2020-11-25T22-57-38
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: client-go
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
