org: istio
repo: client-go
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-07-08T14-39-36

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
