branches:
- release-1.4
image: gcr.io/istio-testing/build-tools:release-1.4-2020-02-14T15-30-45
jobs:
- command:
  - make
  - lint
  name: lint
- name: update-build-tools-image
  type: postsubmit
  command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=test-infra
  - --branch=master
  - "--title=Automator: update build-tools:$AUTOMATOR_SRC_BRANCH"
  - --modifier=buildtools
  - --token-path=/etc/github-token/oauth
  - --script-path=../test-infra/tools/automator/scripts/update-images.sh
  - --
  - --post=make gen
  - --var=IMG
  requirements: [github]
  repos: [istio/test-infra@master]
org: istio
repo: common-files
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
