org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-2020-07-16T22-57-32

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    image: gcr.io/k8s-prow/peribolos:v20200717-96f632166e
    type: postsubmit
    command: [sh, prow/sync-org.sh]
    requirements: [github]
