org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-2020-07-22T15-36-22

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    image: gcr.io/k8s-prow/peribolos:v20200724-b2cdf8399d
    type: postsubmit
    command: [sh, prow/sync-org.sh]
    requirements: [github]
