org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-2020-09-02T23-35-59

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    type: postsubmit
    command: [sh, prow/sync-org.sh]
    requirements: [github]
