org: istio
repo: common-files
image: gcr.io/istio-testing/build-tools:master-2020-04-28T21-48-12

jobs:
  - name: lint
    command: [make, lint]

  - name: update-common
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio,istio.io,api,test-infra,tools,bots,release-builder,pkg,cni,cri,client-go,gogo-genproto,proxy
    - "--title=Automator: update common-files@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --labels=auto-merge
    - --strict
    - --modifier=commonfiles
    - --token-path=/etc/github-token/oauth
    - --cmd=make update-common gen
    requirements: [github]
    repos: [istio/test-infra@master]

  - name: update-build-tools-image
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=test-infra
    - "--title=Automator: update build-tools:$AUTOMATOR_SRC_BRANCH"
    - --branch=master
    - --modifier=buildtools
    - --token-path=/etc/github-token/oauth
    - --script-path=../test-infra/tools/automator/scripts/update-images.sh
    - --verbose
    - --
    - --post=make gen
    - --source=$AUTOMATOR_ROOT_DIR/files/common/scripts/setup_env.sh
    requirements: [github]
    repos: [istio/test-infra@master]