org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-4759bf88d40172234fc6a0b9e11a4c5f1ea58a90

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    types: [postsubmit]
    command: [org-gen, --write-to-github, --github-token=/etc/github-token/oauth]
    node_selector:
      prod: prow
    requirements: [github-organization]
    excluded_requirements: [cache]
    timeout: 4h
    cluster: test-infra-trusted
