org: istio
repo: cri
image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]
