org: istio
repo: enhancements
branches: [master]
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-4759bf88d40172234fc6a0b9e11a4c5f1ea58a90
jobs:
- name: validate-features
  types: [presubmit]
  modifiers: [presubmit_optional]
  command:
    - ../test-infra/scripts/validate_schema.sh
    - --document-path=./features.yaml
    - --schema-path=./features_schema.json
  repos: [istio/test-infra@master,istio/tools@master]
