org: istio
repo: enhancements
branches: [master]
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2021-06-16T23-16-54
jobs:
- name: validate-features
  types: [presubmit]
  modifiers: [optional]
  command:
    - ../test-infra/scripts/validate_schema.sh
    - --document-path=./features.yaml
    - --schema-path=./features_schema.json
  repos: [istio/test-infra@master,istio/tools@master]
