org: istio
repo: gogo-genproto
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2021-03-01T22-30-49

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
