org: istio
repo: istio
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-07-22T15-36-22
jobs:
  - name: unit-tests
    command: [entrypoint, make, -e, "T=-v -count=1", build, racetest, binaries-test]

  - name: release-test
    type: presubmit
    command: [entrypoint, prow/release-test.sh]
    requirements: [gcp, docker]

  - name: release
    type: postsubmit
    command: [entrypoint, prow/release-commit.sh]
    requirements: [gcp, docker]

  - name: benchmark
    type: presubmit
    modifiers: [optional, skipped]
    command: [entrypoint, make, benchtest]
    resources: benchmark

  - name: benchmark-report
    type: postsubmit
    command: [entrypoint, make, benchtest, report-benchtest]
    requirements: [gcp]
    resources: benchmark

  - name: integ-pilot-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-security-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-telemetry-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-multicluster-k8s-tests
    type: presubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --topology
      - MULTICLUSTER
      - test.integration.multicluster.kube.presubmit
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,+multicluster"

  - name: integ-distroless-k8s-tests
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.kube.reachability]
    requirements: [kind]
    env:
      - name: VARIANT
        value: "distroless"
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-ipv6-k8s-tests
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.kube.reachability]
    requirements: [kind]
    env:
      - name: DOCKER_IN_DOCKER_IPV6_ENABLED
        value: "true"
      - name: IP_FAMILY
        value: "ipv6"
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-operator-controller-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.operator.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-pilot-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-pilot-multicluster-tests
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --topology
      - MULTICLUSTER
      - test.integration.pilot.kube
    requirements: [kind]
    modifiers: [optional, hidden, skipped]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-security-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-telemetry-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

    # The node image must be kept in sync with the kind version we use.
    # See istio.io/tools/docker/build-tools for the kind image
    # https://github.com/kubernetes-sigs/kind/releases for node corresponding node image
  - name: integ-k8s-116
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.16.9
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: integ-k8s-117
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.17.5
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: integ-k8s-119
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - gcr.io/istio-testing/kind-node:v1.19.0-rc.2
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: install-cni-test
    modifiers: [hidden, optional]
    command: [entrypoint, make, cni.install-test]
    requirements: [docker]

  - name: analyze-tests
    modifiers: [optional, skipped]
    type: presubmit
    command: [make, test.integration.analyze]

  - name: lint
    type: presubmit
    command: [make, lint]
    resources: lint

  - name: gencheck
    type: presubmit
    command: [make, gen-check]

  - name: release-notes
    type: presubmit
    command:
      - ../test-infra/tools/check_release_notes.sh
      - --token-path=/etc/github-token/oauth
    requirements: [github]
    modifiers:
      - optional
    repos: [istio/test-infra@master]
resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
  # Give 15 CPUs which will put us on a dedicate node, for consistency
  benchmark:
    requests:
      memory: "8Gi"
      cpu: "15000m"
    limits:
      memory: "24Gi"
requirements: [cache]
