org: istio
repo: istio.io
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-08-19T17-29-34

jobs:
  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]

  - name: k8s-tests
    command: [entrypoint, prow/integ-suite-kind.sh, test.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]

  - name: update-ref-docs-dry-run
    type: presubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio.io
    - --token-path=/etc/github-token/oauth
    - --cmd=make update_ref_docs
    - --dry-run
    requirements: [github]
    modifiers: [optional]
    repos: [istio/test-infra@master]

  - name: update-ref-docs
    disable_release_branching: true
    type: periodic
    cron: "0 2 * * *"  # every day at 02:00AM UTC
    command:
    - ./tools/automator/automator.sh
    - --org=istio
    - --repo=istio.io
    - "--title=Automator: update istio.io@$AUTOMATOR_SRC_BRANCH reference docs"
    - --labels=auto-merge,release-notes-none
    - --modifier=refdocs
    - --token-path=/etc/github-token/oauth
    - --cmd=make update_ref_docs
    requirements: [github]
    repos: [istio/test-infra@master]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "5000m"
