org: istio
repo: istio.io
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-05-08T20-48-51

jobs:
  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]

  - name: k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]

  - name: k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.kube.postsubmit]
    requirements: [kind, gcp]

  - name: update-ref-docs-dry-run
    type: presubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio.io
    - --token-path=/etc/github-token/oauth
    - --cmd=make update_ref_docs
    - --dry-run
    requirements: [github]
    modifiers: [optional]
    repos: [istio/test-infra@master]

  - name: update-ref-docs
    type: periodic
    cron: "0 2 * * *"  # every day at 02:00AM UTC
    command:
    - ./tools/automator/automator.sh
    - --org=istio
    - --repo=istio.io
    - "--title=Automator: update istio.io@release-1.6 reference docs"
    - --modifier=refdocs
    - --token-path=/etc/github-token/oauth
    - --cmd=SOURCE_BRANCH_NAME=release-1.6 make update_ref_docs
    requirements: [github]
    repos: [istio/test-infra@master]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "5000m"
