branches:
- release-1.7
image: gcr.io/istio-testing/build-tools:release-1.7-2020-10-12T16-50-25
jobs:
- command:
  - entrypoint
  - make
  - -e
  - T=-v
  - build
  - racetest
  - binaries-test
  name: unit-tests
- command:
  - entrypoint
  - prow/release-test.sh
  name: release-test
  requirements:
  - gcp
  - docker
  type: presubmit
- command:
  - entrypoint
  - prow/release-commit.sh
  name: release
  requirements:
  - gcp
  - docker
  type: postsubmit
- command:
  - entrypoint
  - make
  - benchtest
  modifiers:
  - optional
  - skipped
  name: benchmark
  resources: benchmark
  type: presubmit
- command:
  - entrypoint
  - make
  - benchtest
  - report-benchtest
  name: benchmark-report
  requirements:
  - gcp
  resources: benchmark
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.galley.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-galley-k8s-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.mixer.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-mixer-k8s-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-pilot-k8s-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-security-k8s-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-telemetry-k8s-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.multicluster.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,+multicluster
  name: integ-multicluster-k8s-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: VARIANT
    value: distroless
  - name: TEST_SELECT
    value: -multicluster
  name: integ-distroless-k8s-tests
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: DOCKER_IN_DOCKER_IPV6_ENABLED
    value: "true"
  - name: IP_FAMILY
    value: ipv6
  - name: TEST_SELECT
    value: -multicluster
  name: integ-ipv6-k8s-tests
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.operator.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-operator-controller-tests
  requirements:
  - kind
  type: presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.galley.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-galley-k8s-tests
  requirements:
  - kind
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.mixer.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-mixer-k8s-tests
  requirements:
  - kind
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-pilot-k8s-tests
  requirements:
  - kind
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  modifiers:
  - optional
  - hidden
  - skipped
  name: integ-pilot-multicluster-tests
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-security-k8s-tests
  requirements:
  - kind
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-telemetry-k8s-tests
  requirements:
  - kind
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.16.9
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-116
  requirements:
  - kind
  timeout: 4h0m0s
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.17.5
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-117
  requirements:
  - kind
  timeout: 4h0m0s
  type: postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - gcr.io/istio-testing/kind-node:v1.19.0-rc.1
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-119
  requirements:
  - kind
  timeout: 4h0m0s
  type: postsubmit
- command:
  - entrypoint
  - make
  - cni.install-test
  modifiers:
  - hidden
  - optional
  name: install-cni-test
  requirements:
  - docker
- command:
  - make
  - test.integration.analyze
  modifiers:
  - optional
  - skipped
  name: analyze-tests
  type: presubmit
- command:
  - make
  - lint
  name: lint
  resources: lint
  type: presubmit
- command:
  - make
  - gen-check
  name: gencheck
  type: presubmit
- command:
  - ../test-infra/tools/check_release_notes.sh
  - --token-path=/etc/github-token/oauth
  name: release-notes
  repos: [istio/test-infra@master,istio/tools@master]
  requirements:
  - github
  type: presubmit
org: istio
repo: istio
resources:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  default:
    limits:
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
