org: istio
repo: istio
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-04-16T19-28-05

jobs:
  - name: unit-tests
    requirements: [cache]
    command: [entrypoint, make, -e, "T=-v", build, racetest, binaries-test]

  - name: cache-experiment
    requirements: [cache, kind]
    modifiers: [optional, hidden]
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube.presubmit]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: release-test
    type: presubmit
    command: [entrypoint, prow/release-test.sh]
    requirements: [gcp]

  - name: release
    type: postsubmit
    command: [entrypoint, prow/release-commit.sh]
    requirements: [gcp]

  - name: integ-galley-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.galley.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-mixer-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.mixer.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-pilot-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-security-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-telemetry-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-multicluster-k8s-tests
    type: presubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --topology
      - MULTICLUSTER_SINGLE_NETWORK
      - test.integration.kube.presubmit
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,+multicluster"

  - name: integ-distroless-k8s-tests
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.kube.reachability]
    requirements: [kind]
    env:
      - name: VARIANT
        value: "distroless"
      - name: TEST_SELECT
        value: "-multicluster"

  # - name: integ-ipv6-k8s-tests
  #   command: [entrypoint, prow/integ-suite-kind.sh, test.integration.kube.reachability]
  #   requirements: [kind]
  #   modifiers: [optional, hidden]
  #   env:
  #     - name: DOCKER_IN_DOCKER_IPV6_ENABLED
  #       value: "true"
  #     - name: IP_FAMILY
  #       value: "ipv6"
  #     - name: TEST_SELECT
  #       value: "-multicluster"

  - name: integ-conformance-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-operator-controller-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.operator.kube.presubmit]
    requirements: [kind]
    modifiers: [optional, hidden]
    env:
      - name: TEST_SELECT
        value: "-postsubmit,-flaky,-multicluster"

  - name: integ-local-tests
    command: [entrypoint, prow/integ-suite-local.sh, test.integration...local]
    requirements: [docker]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-galley-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.galley.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-mixer-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.mixer.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-pilot-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-security-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-telemetry-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-conformance-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube]
    requirements: [kind]
    env:
      - name: TEST_SELECT
        value: "-multicluster"

    # The node image must be kept in sync with the kind version we use.
    # See docker/istio/shared/tools/install-golang.sh for the kind image
    # https://github.com/kubernetes-sigs/kind/releases for node corresponding node image
  - name: integ-k8s-115
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.15.7
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-k8s-116
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.16.4
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "
      - name: TEST_SELECT
        value: "-multicluster"

  - name: integ-k8s-117
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.17.2
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: integ-k8s-119
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - gcr.io/istio-testing/kind-node:v1.19.0-alpha.1
      - test.integration.kube.presubmit
    requirements: [kind]
    modifiers: [hidden]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: lint
    type: presubmit
    command: [make, lint]
    resources: lint

  - name: gencheck
    type: presubmit
    command: [make, gen-check]

  - name: update-ref-docs-dry-run
    type: presubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio.io
    - --token-path=/etc/github-token/oauth
    - --cmd=make update_ref_docs
    - --dry-run
    requirements: [github]
    modifiers: [optional]
    repos: [istio/test-infra]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
