branches:
- release-1.5
image: gcr.io/istio-testing/build-tools:release-1.5-2020-05-11T22-26-45
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - test
  name: test
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: pkg
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
