branches:
- release-1.7
image: gcr.io/istio-testing/build-tools:release-release-1.7-2020-07-16T22-57-32
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - test
  name: test
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: pkg
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
