branches:
- release-1.8
image: gcr.io/istio-testing/build-tools:release-1.8-2020-10-15T20-33-46
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - test
  name: test
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: pkg
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
