org: istio
repo: pkg
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2021-01-29T01-18-46

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]
