org: istio
repo: pkg
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-12-09T23-05-01

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]
