org: istio
repo: proxy
support_release_branching: true
image: gcr.io/istio-testing/build-tools-proxy:master-2020-10-30T04-19-52
node_selector:
  testing: build-pool

jobs:
- name: test
  type: presubmit
  command: [./prow/proxy-presubmit.sh]
  timeout: 4h

- name: test-asan
  type: presubmit
  command: [./prow/proxy-presubmit-asan.sh]
  timeout: 4h

- name: test-tsan
  type: presubmit
  command: [./prow/proxy-presubmit-tsan.sh]
  timeout: 4h

- name: release-test
  type: presubmit
  command: [./prow/proxy-presubmit-release.sh]
  requirements: [gcp]
  timeout: 4h

- name: release-centos-test
  type: presubmit
  command: [./prow/proxy-presubmit-centos-release.sh]
  requirements: [gcp]
  image: gcr.io/istio-testing/build-tools-centos:master-2020-10-30T04-19-52
  # Current optional until further testing is done to ensure stability
  modifiers: [optional]
  timeout: 4h

- name: check-wasm
  type: presubmit
  command: [entrypoint, ./prow/proxy-presubmit-wasm.sh]
  requirements: [docker]
  timeout: 4h

- name: release
  type: postsubmit
  command: [entrypoint, ./prow/proxy-postsubmit.sh]
  requirements: [gcp, docker]
  timeout: 4h

- name: release-centos
  type: postsubmit
  command: [./prow/proxy-postsubmit-centos.sh]
  requirements: [gcp]
  image: gcr.io/istio-testing/build-tools-centos:master-2020-10-30T04-19-52
  timeout: 4h

- name: update-istio
  type: postsubmit
  command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio
  - "--title=Automator: update proxy@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
  - --labels=auto-merge,release-notes-none
  - --modifier=update_proxy_dep
  - --token-path=/etc/github-token/oauth
  - --cmd=bin/update_proxy.sh $AUTOMATOR_SHA
  requirements: [github]
  repos: [istio/test-infra@master]
  image: gcr.io/istio-testing/build-tools:master-2020-10-30T04-19-52
  timeout: 4h

resources:
  default:
    requests:
      memory: "100G"
      cpu: "30"
    limits:
      memory: "240G"
      cpu: "64"
