branches:
- release-1.5
image: gcr.io/istio-testing/build-tools-proxy:release-1.5-2020-05-11T22-26-45
jobs:
- command:
  - ./prow/proxy-presubmit.sh
  name: test
  types: [presubmit]
- command:
  - ./prow/proxy-presubmit-asan.sh
  name: test-asan
  types: [presubmit]
- command:
  - ./prow/proxy-presubmit-tsan.sh
  name: test-tsan
  types: [presubmit]
- command:
  - ./prow/proxy-presubmit-release.sh
  name: release-test
  requirements:
  - gcp
  types: [presubmit]
- command:
  - entrypoint
  - ./prow/proxy-presubmit-wasm.sh
  name: check-wasm
  requirements:
  - docker
  types: [presubmit]
- command:
  - entrypoint
  - ./prow/proxy-postsubmit.sh
  name: release
  requirements:
  - gcp
  - docker
  timeout: 4h
  types: [postsubmit]
org: istio
repo: proxy
resources:
  default:
    limits:
      cpu: "16"
      memory: 60Gi
    requests:
      cpu: "8"
      memory: 8Gi
