org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:master-2020-05-31T23-50-32

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: unit-test-authentikos
    type: presubmit
    # trigger on changes in `authentikos/` directory to the following:
    # - `.go`    : Golang source files. When the source code changes, test the validity of the change.
    # - `go.mod` : Golang module dependencies. When the dependencies change, test the compatibility of the change.
    regex: '^authentikos/(.+\.go|go\.mod)$'
    command: [make, -C, authentikos, unit-test]

  - name: integ-test-authentikos
    type: presubmit
    # trigger on changes in `authentikos/` directory to the following:
    # - `test/`  : integration test library, scripts, and object configuration files.
    #              If there are changes to the tests themselves, run the modified tests.
    # - `.go`    : Golang source files. When the source code changes, test the validity of the change.
    # - `go.mod` : Golang module dependencies. When the dependencies change, test the compatibility of the change.
    regex: '^authentikos/(test/.+|.+\.go|go\.mod)$'
    command: [entrypoint, make, -C, authentikos, integ-test]
    requirements: [kind, gcp]

  - name: deploy-prow
    type: postsubmit
    regex: '^prow/cluster/(?:gcsweb/|velodrome/|monitoring/|build/|private/|[^/]+\.yaml$)'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - prow
    - deploy
    - deploy-gcsweb
    - deploy-velodrome
    - deploy-monitoring
    - deploy-build
    - deploy-private
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: deploy-boskos
    type: postsubmit
    regex: '^boskos/cluster/.*\.yaml$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - deploy
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: deploy-boskos-config
    type: postsubmit
    regex: '^boskos/resources.yaml$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - boskos-config
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: push-mason
    type: postsubmit
    regex: '^boskos/cmd/mason/.+'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - mason-image
    requirements: [docker, gcp]
    node_selector:
        prod: prow

  - name: push-prowbazel
    type: postsubmit
    regex: '^docker/prowbazel/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - docker/prowbazel
    - image
    - push-safe
    requirements: [docker, gcp]
    node_selector:
        prod: prow

  - name: push-authentikos
    type: postsubmit
    regex: '^authentikos/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - authentikos
    - deploy
    requirements: [docker, gcp]
    node_selector:
      prod: prow

  - name: push-genjobs
    type: postsubmit
    regex: '^prow/genjobs/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - prow/genjobs
    - deploy
    requirements: [docker, gcp]
    node_selector:
      prod: prow

  - name: bump-k8s-prow-images
    type: periodic
    cron: "05 15-23 * * 1-5"  # Run at 7:05-15:05 PST (15:05 UTC) Mon-Fri
    command:
    - ./tools/automator/automator.sh
    - --org=istio
    - --repo=test-infra
    - "--title=Automator: bump k8s-prow images"
    - --modifier=bump-k8s-prow-images
    - --token-path=/etc/github-token/oauth
    - --script-path=../test-infra/tools/automator/scripts/update-images.sh
    - --verbose
    - --
    - --paths=prow/cluster/jobs/**/!(*test-infra*).yaml,prow/config/jobs/**/!(*test-infra*).yaml
    - --source=$AUTOMATOR_ROOT_DIR/prow/cluster/plank_deployment.yaml
    - --image=gcr.io/k8s-prow/.*
    - --tag=v[0-9]{8}-[a-f0-9]{10}
    - --var=image
    requirements: [github]
    repos: [istio/test-infra]