org: istio
repo: tools
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-05-28T00-40-33

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: benchmark_check
    disable_release_branching: true
    regex: '^perf/benchmark/'
    type: presubmit
    command: [entrypoint, ./perf/benchmark/run_benchmark_job.sh]
    env:
      - name: TRIALRUN
        value: "True"
    modifiers: [optional]
    requirements: [gcp]

  - name: containers
    type: postsubmit
    command: [entrypoint, make, containers]
    resources: build
    regex: 'docker/.+|cmd/.+'
    requirements: [gcp, docker]

  - name: containers-test
    type: presubmit
    command: [entrypoint, make, containers-test]
    resources: build
    regex: 'docker/.+|cmd/.+'
    requirements: [gcp, docker]

  - name: deploy-perf-dashboard
    regex: '^perf_dashboard/'
    type: postsubmit
    command: [entrypoint, make, -C, perf_dashboard, deploy]
    requirements: [docker, gcp]

resources:
  build:
    requests:
      memory: "4Gi"
      cpu: "8000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
