org: istio
repo: ztunnel
image: gcr.io/istio-testing/build-tools:master-4759bf88d40172234fc6a0b9e11a4c5f1ea58a90
support_release_branching: true

jobs:
  - name: test
    command: [entrypoint, make, presubmit]
    requirements: [cratescache]

  - name: bench
    command: [entrypoint, ./scripts/benchtest.sh]
    modifiers: [presubmit_optional, presubmit_skipped]
    types: [presubmit]
    requirements: [cratescache]

  - name: coverage
    command: [entrypoint, make, coverage]
    types: [postsubmit]
    requirements: [cratescache]

  - name: release
    architectures: [amd64, arm64]
    service_account_name: prowjob-testing-write
    types: [postsubmit]
    command: [make, release]
    requirements: [cratescache]

resources_presets:
  # Rust jobs are CPU intensive. Bump up defaults (from 1/3) to 3/8 to speed up jobs.
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
