org: istio
repo: ztunnel
image: gcr.io/istio-testing/build-tools:master-5acc674b22171cccc9b650f4e9c4eb417fa345b7

jobs:
  - name: test
    command: [make, presubmit]
    requirements: [cratescache]

  - name: release
    service_account_name: prowjob-advanced-sa
    types: [postsubmit]
    command: [make, release]
    requirements: [cratescache]
