resources:
- name: type2
  min-count: 1
  needs:
    type1: 1
  config:
    type: GCPResourceConfig
    content: |
      type1:
        - clusters:
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.17
            zone: us-central-1f
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
            enableworkloadidentity: true
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180105
            zone: us-central-1f
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
- name: type3
  min-count: 1
  needs:
    type1: 1
  config:
    type: GCPResourceConfig
    content: |
      type1:
        - clusters:
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.17
            zone: us-central-1f
            networkpolicy:
              enabled: true
              provider: CALICO
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180105
            zone: us-central-1f
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
- name: type4
  min-count: 1
  needs:
    type1: 1
  config:
    type: GCPResourceConfig
    content: |
      type1:
        - clusters:
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.17
            zone: us-central-1f
            releasechannel:
               channel: RAPID
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180105
            zone: us-central-1f
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
