apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "authentikos-token"
  namespace: "test-pods"
spec:
  backendType: gcpSecretsManager
  projectId: "istio-prow-build"
  dataFrom:
  - "gke_istio-prow-build_us-west1-a_prow-private__test-pods__authentikos-token" # Secret name in GSM
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "cosign-key"
  namespace: "test-pods"
spec:
  backendType: gcpSecretsManager
  projectId: "istio-prow-build"
  dataFrom:
  - "gke_istio-prow-build_us-west1-a_prow-private__test-pods__cosign-key" # Secret name in GSM
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "gitconfig"
  namespace: "test-pods"
spec:
  backendType: gcpSecretsManager
  projectId: "istio-prow-build"
  dataFrom:
  - "gke_istio-prow-build_us-west1-a_prow-private__test-pods__gitconfig" # Secret name in GSM
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "netrc-secret"
  namespace: "test-pods"
spec:
  backendType: gcpSecretsManager
  projectId: "istio-prow-build"
  dataFrom:
  - "gke_istio-prow-build_us-west1-a_prow-private__test-pods__netrc-secret" # Secret name in GSM
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "ssh-key-secret"
  namespace: "test-pods"
spec:
  backendType: gcpSecretsManager
  projectId: "istio-prow-build"
  dataFrom:
  - "gke_istio-prow-build_us-west1-a_prow-private__test-pods__ssh-key-secret" # Secret name in GSM
---
