apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prowjob-private@istio-prow-private.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/part-of: prow-private
  namespace: test-pods
  # Default service account that only has permissions to access the GCS buckets for private build.
  name: prowjob-private
