---
gitHubLogin: "istio-testing"
gitHubToken: "/etc/github-token/oauth"
onCallAddress: "https://storage.googleapis.com/kubernetes-jenkins/oncall.json"
skipPullRequest: false
selfAssign: true # Commenting `/cc`, so that autobump PR is not assigned to anyone
gitHubOrg: "istio"
gitHubRepo: "test-infra"
remoteName: "test-infra"
headBranchName: "autobump-prow"
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
includedConfigPaths:
  - prow/cluster
targetVersion: "upstream"
extraFiles:
  - ".prow.yaml"
  - "prow/config.yaml"
prefixes: 
  - name: "Prow"
    prefix: "gcr.io/k8s-prow/"
    repo: "https://github.com/kubernetes/test-infra"
    refConfigFile: "config/prow/cluster/deck_deployment.yaml"
    summarise: false
    consistentImages: true
    # These images do not have 1:1 versions
    consistentImageExceptions:
    - "gcr.io/k8s-prow/alpine"
    - "gcr.io/k8s-prow/analyze"
    - "gcr.io/k8s-prow/commenter"
    - "gcr.io/k8s-prow/configurator"
    - "gcr.io/k8s-prow/gcsweb"
    - "gcr.io/k8s-prow/gencred"
    - "gcr.io/k8s-prow/git"
    - "gcr.io/k8s-prow/issue-creator"
    - "gcr.io/k8s-prow/label_sync"
    - "gcr.io/k8s-prow/pr-creator"