# Plugin repository allowlist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio
  - istio-ecosystem
  - istio-private
  trusted_org: istio

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/cluster/jobs/**/*.yaml:
      name: job-config
      gzip: true

slack:
  mergewarnings:
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    exempt_users:
    - istio-testing

lgtm:
- repos:
  - istio
  review_acts_as_lgtm: true
- repos:
  - istio-ecosystem/authservice
  review_acts_as_lgtm: true

approve:
- repos:
  - istio-ecosystem/authservice
  require_self_approval: false

plugins:
  istio:
  - size
  - trigger
  - wip

  istio-ecosystem:
  - size
  - trigger
  - wip

  istio-private:
  - trigger

  istio/test-infra:
  - assign
  - config-updater
  - golint
  - hold
  - lifecycle
  - skip
  - slackevents

  istio-ecosystem/authservice:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - verify-owners

external_plugins:
  istio:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
  istio-ecosystem/authservice:
  - name: needs-rebase
    events:
    - pull_request
